export const CREATEMESSAGE_REQUEST = "CREATEMESSAGE_REQUEST";
export const CREATEMESSAGE_SUCCESS = "CREATEMESSAGE_SUCCESS";
export const CREATEMESSAGE_ERROR = "CREATEMESSAGE_ERROR";

export const MESSAGESENDER_REQUEST = "MESSAGESENDER_REQUEST";
export const MESSAGESENDER_SUCCESS = "MESSAGESENDER_SUCCESS";
export const MESSAGESENDER_ERROR = "MESSAGESENDER_ERROR";