export const TICKETDETAILS_REQUEST = "TICKETDETAILS_REQUEST";
export const TICKETDETAILS_SUCCESS = "TICKETDETAILS_SUCCESS";
export const TICKETDETAILS_ERROR = "TICKETDETAILS_ERROR";

export const SENDERDETAILS_REQUEST = "SENDERDETAILS_REQUEST";
export const SENDERDETAILS_SUCCESS = "SENDERDETAILS_SUCCESS";
export const SENDERDETAILS_ERROR = "SENDERDETAILS_ERROR";