export const TIKETS_REQUEST = "TICKETS_REQUEST";
export const TIKETS_SUCCESS = "TICKETS_SUCCESS";
export const TIKETS_ERROR = "TICKETS_ERROR";
export const TICKETS_TOGGLE = "TICKETS_TOGGLE";

export const TIKETTYPES_REQUEST = "TIKETTYPES_REQUEST";
export const TIKETTYPES_SUCCESS = "TIKETTYPES_SUCCESS";
export const TIKETTYPES_ERROR = "TIKETTYPES_ERROR";

export const TIKETSTATUSES_REQUEST = "TIKETSTATUSES_REQUEST";
export const TIKETSTATUSES_SUCCESS = "TIKETSTATUSES_SUCCESS";
export const TIKETSTATUSES_ERROR = "TIKETSTATUSES_ERROR";
