export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

export const USERDETAILS_REQUEST = "USERDETAILS_REQUEST";
export const USERDETAILS_SUCCESS = "USERDETAILS_SUCCESS";
export const USERDETAILS_ERROR = "USERDETAILS_ERROR";
